### ISSUE TITLE
Trouble when run to Sentinel 2

### ISSUE THREAD

**Issue by diogocaribe** [ubarsc/python-fmask#34]
I've received this error when run package with Sentinel 2 file:

It was run in python 3.8.1, with gdal GDAL 2.2.3, Ubuntu 18.04, with pythonfmask-0.5.4.

```python
fmask_sentinel2Stacked.py -o cloud.img --safedir ./img_files/S2A_MSIL1C_20200311T125301_N0209_R052_T24LXN_20200311T160933.SAFE
Traceback (most recent call last):
  File "/home/diogo/.ve/fmask/bin/fmask_sentinel2Stacked.py", line 22, in <module>
    sentinel2Stacked.mainRoutine()
  File "/home/diogo/.ve/fmask/lib/python3.8/site-packages/fmask/cmdline/sentinel2Stacked.py", line 311, in mainRoutine
    fmask.doFmask(fmaskFilenames, fmaskConfig)
  File "/home/diogo/.ve/fmask/lib/python3.8/site-packages/fmask/fmask.py", line 157, in doFmask
    potentialShadowsFile = doPotentialShadows(fmaskFilenames, fmaskConfig, NIR_17)
  File "/home/diogo/.ve/fmask/lib/python3.8/site-packages/fmask/fmask.py", line 725, in doPotentialShadows
    scaledNIR_filled = fillminima.fillMinima(scaledNIR, nullval, NIR_17_dn)
  File "/home/diogo/.ve/fmask/lib/python3.8/site-packages/fmask/fillminima.py", line 72, in fillMinima
    fillminima.fillMinima(img, img2, hMin, hMax, nullmask, boundaryval,
TypeError: fillMinima() takes 3 positional arguments but 8 were given

```

**Comment by diogocaribe** [comment]
It doesn't matter. I've forgotten to install package.
