### ISSUE TITLE
Copernicus Sentinel-2 Major Products Upgrade on 2021/10/26

### ISSUE THREAD

**Issue by davidmichea** [ubarsc/python-fmask#47]
Hi,

Considering this annoucement :

https://sentinels.copernicus.eu/web/sentinel/-/copernicus-sentinel-2-major-products-upgrade-upcoming-l1c-and-l2a-sample-products

I tried fmask on a sample of the new SAFE format (can be found [here](https://sentinels.copernicus.eu/web/sentinel/-/copernicus-sentinel-2-major-products-upgrade-upcoming-l1c-and-l2a-sample-products)) and it seems broken:
`
fmask_sentinel2Stacked.py -o mask.tif --granuledir ./S2B_MSIL1C_20210517T103619_N7990_R008_T30QVE_20210929T075738.SAFE/GRANULE
Traceback (most recent call last):
  File "/b/home/ipgs/a2s_prod/A2S/installs/venv_a2s/bin/fmask_sentinel2Stacked.py", line 22, in <module>
    sentinel2Stacked.mainRoutine()
  File "/b/home/ipgs/a2s_prod/A2S/installs/venv_a2s/lib/python3.6/site-packages/fmask/cmdline/sentinel2Stacked.py", line 285, in mainRoutine
    resampledBands = makeStackAndAngles(cmdargs)
  File "/b/home/ipgs/a2s_prod/A2S/installs/venv_a2s/lib/python3.6/site-packages/fmask/cmdline/sentinel2Stacked.py", line 177, in makeStackAndAngles
    sentinel2makeAnglesImage.makeAngles(xmlfile, anglesfile)
  File "/b/home/ipgs/a2s_prod/A2S/installs/venv_a2s/lib/python3.6/site-packages/fmask/cmdline/sentinel2makeAnglesImage.py", line 86, in makeAngles
    info = sen2meta.Sen2TileMeta(filename=infile)
  File "/b/home/ipgs/a2s_prod/A2S/installs/venv_a2s/lib/python3.6/site-packages/fmask/sen2meta.py", line 43, in __init__
    f = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: './S2B_MSIL1C_20210517T103619_N7990_R008_T30QVE_20210929T075738.SAFE/GRANULE/MTD_TL.xml'
`

Is there a workaround ?

best regards
David

**Comment by davidmichea** [comment]
Thanks a lot for the information Neil
