### ISSUE TITLE
cannot import name '_fillminima' from 'fmask'

### ISSUE THREAD

**Issue by hastaluegoph** [ubarsc/python-fmask#68]
I want to run fmask to process the sentinel2 cloud and I install the fmask following the install.txt.and then I get the error:
Traceback (most recent call last):
  File "/home/penghan/work/python_fmask/bin/fmask_sentinel2Stacked.py", line 19, in <module>
    from fmask.cmdline import sentinel2Stacked
  File "/home/penghan/work/python_fmask/fmask/cmdline/sentinel2Stacked.py", line 38, in <module>
    from fmask import fmask
  File "/home/penghan/work/python_fmask/fmask/fmask.py", line 64, in <module>
    from . import fillminima
  File "/home/penghan/work/python_fmask/fmask/fillminima.py", line 37, in <module>
    from . import _fillminima
ImportError: cannot import name '_fillminima' from 'fmask' (/home/penghan/work/python_fmask/fmask/__init__.py)

**Comment by gillins** [comment]
You'll need to install `python-fmask` first with a command line `pip install .`. Then you should be able to run `fmask_sentinel2Stacked.py` etc (it pays to `cd` out of the source after installing).
Alternatively you can use conda-forge.

**Comment by hastaluegoph** [comment]
Thanks a lot! I find it runs well when I change the main directory
